### ISSUE TITLE
similar repo & feature request

### ISSUE THREAD

**Issue by lgh06** [antonholmberg/android-emulator#3]
https://github.com/wswebcreation/start-android-emulator

**Comment by lgh06** [comment]
And , your repo is also interaction needed.  
feature request see: 
https://github.com/wswebcreation/start-android-emulator/issues/3

**Comment by antonholmberg** [comment]
I'm sorry but I have a hard time understanding what the feature request is about. Do you want to be able to set default emulator and launch that one if the `--default` flag is on?

**Comment by lgh06** [comment]
This script is interaction needed, how about adding a `--silent` param, then all options use default value or last time specified value. Then I can `android-emulator --silent && other-tasks-maybe`
